### ISSUE TITLE
Unable to use ssh from inside `nix run` shell

### ISSUE THREAD

**Issue by ghost** [t184256/nix-in-termux#2] opened 2019-03-11 20:45 UTC
```sh
./nix-in-termux nix run nixpkgs.bashInteractive
> ssh
```
outputs:
```
No user exist for uid 10161
```

**Comment by t184256** [comment] 2019-03-12 07:36
That's an easy one, you just need an /etc/passwd entry.

Another project of mine, a followup to this one, [has a fix for that](https://github.com/t184256/nix-on-droid-bootstrap/blob/8629f29639bf25245c0b23b424f0f315b2704761/script#L100).
At this point I advise you to [try that one](https://nix-on-droid.unboiled.info/) instead as I've shifted my efforts. Sorry for the inconvenience.

**Comment by ghost** [comment] 2019-03-12 09:41
Got it. Thank you!

I tried Nix-on-Droid and got this error:

```
Installing home-manager...
GC Warning: Couldn't read /proc/stat
GC Warning: Couldn't read /proc/stat
these derivations will be built:
/nix/store/6n2w6f1g3rsdrlwl1pbfnxpp9qwrqazb-home-manager.drv
GC Warning: Couldn't read /proc/stat
building '/nix/store/6n2w6f1g3rsdrlwl1pbfnxpp9qwrqazb-home-manager.drv'...
/nix/store/v262b100wnfjhyxjv5bk2zachznf3147-stdenv-linux/setup: line 1259: 24434 Bus error install -v -D -m755 /nix/store/3a2whifgkajbm618v1xx94j8llbm199a-home-manager $out/bin/home-manager
builder for '/nix/store/6n2w6f1g3rsdrlwl1pbfnxpp9qwrqazb-home-manager.drv' failed with exit code 135
error: build of '/nix/store/6n2w6f1g3rsdrlwl1pbfnxpp9qwrqazb-home-manager.drv' failed
```

Also, I can not make it work with smth. like Termux:Style (not sure if it possible)

Should I file different issue?

**Comment by t184256** [comment] 2019-03-12 10:11
> /nix/store/v262b100wnfjhyxjv5bk2zachznf3147-stdenv-linux/setup: line 1259: 24434 Bus error 

Aargh, not this thing again.

> Should I file different issue?

Sure, please file it against https://github.com/t184256/nix-on-droid-bootstrap and try to include more details about your OS/device. I cannot reproduce this one. =/

Meanwhile you can close it, open the failsafe shell and modify `/data/data/com.termux.nix/files/usr/bin/.login-inner` until I modify it to make more steps optional.

> Also, I can not make it work with smth. like Termux:Style (not sure if it possible)

It is supposed to be integrated into the app already.

**Closed as completed** 2019-03-12 12:59 UTC
